# Generated by Django 5.1.2 on 2024-10-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="money_to_pay",
            new_name="total_amount",
        ),
    ]
