# Generated by Django 5.1.2 on 2024-10-17 13:28

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=books.models.book_image_file_path
            ),
        ),
    ]
