# Generated by Django 5.1.2 on 2024-10-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_author_options_alter_genre_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["id", "title", "year"]},
        ),
        migrations.AddField(
            model_name="book",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
