# Generated by Django 5.1.2 on 2024-10-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_alter_checkout_checkout_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkout",
            options={"ordering": ["-checkout_date"]},
        ),
    ]
