# Generated by Django 5.1.2 on 2024-10-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_alter_checkout_checkout_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="checkout_date",
            field=models.DateField(blank=True),
        ),
    ]
